language: python
python:
  - "3.6"
  - "3.5"


install:
   - pip install -r requirements.txt
script: 
  nosetests --with-coverage --cover-package=models && coverage report
  coveralls
after_success:
  coveralls